# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Week2_Test_ATK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Week2_Test_ATK
pod 'URLImage'
end
